apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo
spec:
  selector:
    app.kubernetes.io/name: todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080